version: 2.1
orbs:
description: "Install GCP CLI, if needed, and configure. Build and push image to repository.\n"
jobs: 
  build-image: 
    attach-workspace: <<parameters.attach-workspace>>
    docker-context: <<parameters.docker-context>>
    extra_build_args: <<parameters.extra_build_args>>
    google-project-id: <<parameters.google-project-id>>
    image: <<parameters.image>>
    no_output_timeout: <<parameters.no_output_timeout>>
    path: <<parameters.path>>
    registry-url: <<parameters.registry-url>>
    tag: <<parameters.tag>>
    workspace-root: <<parameters.workspace-root>>
  gcr-auth: 
    gcloud-service-key: <<parameters.gcloud-service-key>>
    google-compute-zone: <<parameters.google-compute-zone>>
    google-project-id: <<parameters.google-project-id>>
  push-image: 
    digest-path: <<parameters.digest-path>>
    google-project-id: <<parameters.google-project-id>>
    image: <<parameters.image>>
    registry-url: <<parameters.registry-url>>
    tag: <<parameters.tag>>
orbs: ~
parameters: 
  attach-workspace: 
    default: false
    description: "Boolean for whether or not to attach to an existing workspace. Default is false.\n"
    type: boolean
  digest-path: 
    default: ""
    description: "(Optional) The path to save the RepoDigest of the pushed image"
    type: string
  docker-context: 
    default: "."
    description: "Path to the directory containing your build context, defaults to . (working directory)\n"
    type: string
  dockerfile: 
    default: Dockerfile
    description: "Name of dockerfile to use, defaults to Dockerfile"
    type: string
  extra_build_args: 
    default: ""
    description: "Extra flags to pass to docker build. For examples, see https://docs.docker.com/engine/reference/commandline/build\n"
    type: string
  gcloud-service-key: 
    default: GCLOUD_SERVICE_KEY
    description: "The gcloud service key"
    type: string
  google-compute-zone: 
    default: GOOGLE_COMPUTE_ZONE
    description: "The Google compute zone to connect with via the gcloud CLI"
    type: string
  google-project-id: 
    default: GOOGLE_PROJECT_ID
    description: "The Google project ID to connect with via the gcloud CLI"
    type: string
  image: 
    default: ""
    description: "A name for your Docker image"
    type: string
  no_output_timeout: 
    default: 10m
    description: "Pass through a default timeout if your Docker build does not output anything for more than 10 minutes.\n"
    type: string
  path: 
    default: "."
    description: "Path to the directory containing your Dockerfile, defaults to . (working directory)\n"
    type: string
  registry-url: 
    default: gcr.io
    description: "The GCR registry URL from ['', us, eu, asia].gcr.io"
    type: string
  setup-remote-docker: 
    default: false
    description: "Setup and use CircleCI's remote Docker environment for Docker and docker-compose commands? Not required if using the default executor\n"
    type: boolean
  string: 
    default: string
    description: "string to use for this job"
    type: string
  tag: 
    default: latest
    description: "A Docker image tag"
    type: string
  use-docker-layer-caching: 
    default: false
    description: "Setup docker layer caching for optimized build. Not available if using the default executor.\n"
    type: boolean
  workspace-root: 
    default: "."
    description: "Workspace root path that is either an absolute path or a path relative to the working directory. Defaults to '.' (the working directory)\n"
    type: string
string: <<parameters.string>>
version: 2.1
workflows: 
  workflow: 
    jobs: 
      - gcr-auth
      - build-image
      - push-image
 
